services:
  test:
    build: .
    image: retry-handler-env
    command: mvn test
    volumes:
      - .:/app
    working_dir: /app/repository_after

  evaluation:
    image: retry-handler-env
    command: python3 evaluation/evaluation.py
    volumes:
      - .:/app
    depends_on:
      - test
    working_dir: /app
