services:
  test:
    build: .
    image: tracestitcher-app
    command: pytest -v --cov=repository_after tests/
    volumes:
      - .:/app

  evaluation:
    build: .
    image: tracestitcher-app
    command: python3 evaluation/evaluation.py
    volumes:
      - .:/app
