# Docker Compose file for running tests. You should customize this as needed.

services:
  app:
    build: .
    command: node evaluation/evaluator.js
    environment:
      - NODE_OPTIONS=--experimental-vm-modules
    volumes:
      - .:/app
