version: "3.8"

services:
  test:
    build: .
    working_dir: /app/repository_after
    command: mvn -Dmaven.test.failure.ignore=false clean test
    volumes:
      - .:/app

  meta-test:
    build: .
    working_dir: /app
    command: python3 tests/meta_test.py
    volumes:
      - .:/app

  evaluation:
    build: .
    working_dir: /app
    command: python3 evaluation/evaluation.py
    volumes:
      - .:/app
