services:
  test-after:
    build: .
    volumes:
      - .:/app
    command: pytest -q tests/after_test.py

  meta-test:
    build: .
    volumes:
      - .:/app
    command: pytest -q tests/meta_test.py

  evaluation:
    build: .
    volumes:
      - .:/app
    command: python3 evaluation/Evaluation.py
