version: "3.8"

services:
  # Service to run tests
  tests:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./:/app
    command: python -m pytest ./repository_after/test/ -v --tb=short
    environment:
      - PYTHONPATH=/app
  # Service to run evaluation
  evaluation:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./:/app
    command: python evaluation/evaluation.py
    environment:
      - PYTHONPATH=/app
