version: "3.8"

services:
  app:
    build:
      context: ./repository_after
    ports:
      - "3000:3000"
    environment:
      - DATABASE_URL=postgresql://postgres:postgres@db:5432/postgres
    depends_on:
      - db
    command: sh -c "npx prisma generate && npx prisma db push && npm run build && npm start"
    volumes:
      - ./repository_after:/app
      - /app/node_modules

  test:
    build:
      context: ./repository_after
    environment:
      - DATABASE_URL=postgresql://postgres:postgres@db:5432/postgres
      - TEST_ROOT=/app/tests
      - BASE_URL=http://app:3000
    depends_on:
      - db
      - app
    volumes:
      - ./repository_after:/app
      - /app/node_modules
      - ./tests:/app/tests
    command: sh -c "rm -f /app/test_output.txt && npx prisma generate && npx prisma db push && npx jest --coverage --no-cache > /app/test_output.txt 2>&1"

  evaluation:
    build:
      context: ./repository_after
    environment:
      - DATABASE_URL=postgresql://postgres:postgres@db:5432/postgres
      - TEST_ROOT=/app/tests
    depends_on:
      - db
    volumes:
      - ./repository_after:/app
      - /app/node_modules
      - ./evaluation:/app/evaluation
      - ./tests:/app/tests
    command: npx ts-node /app/evaluation/evaluation.ts

  db:
    image: postgres:15-alpine
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 2s
      timeout: 5s
      retries: 10

volumes:
  postgres_data:
