# Docker Compose file for running tests. You should customize this as needed.

services:
  app:
    build: .
    command: bash -c "cd /app/tests && make clean && make REPO_DIR=${REPO_DIR:-repository_after} && ./record_processor"
    volumes:
      - .:/app
    environment:
      - REPO_DIR=${REPO_DIR:-repository_after}
