# Docker Compose file for running tests. You should customize this as needed.

services:
  app:
    build: .
    command: sh -c "cmake -S . -B build && cmake --build build && ./build/bin/record_processor"
    volumes:
      - .:/app
