services:
  repo-before:
    build:
      context: .
      dockerfile: Dockerfile
    working_dir: /app/repository_after
    environment:
      - CI=true
      - FORCE_COLOR=0
    command: npm test

  repo-after:
    build:
      context: .
      dockerfile: Dockerfile
    working_dir: /app/tests
    environment:
      - CI=true
      - FORCE_COLOR=0
    command: sh -c "npm install && npm test"

  evaluation:
    build:
      context: .
      dockerfile: Dockerfile
    working_dir: /app
    environment:
      - CI=true
      - FORCE_COLOR=0
    command: node evaluation/evaluation.js
