version: "3.8"

services:
  test-before:
    image: dataprocessing-test
    build: .
    volumes:
      - .:/app
      - maven-repo:/root/.m2
    command: mvn test -B -Pbefore
    working_dir: /app

  test-after:
    image: dataprocessing-test
    build: .
    volumes:
      - .:/app
      - maven-repo:/root/.m2
    command: mvn test -B -Pafter
    working_dir: /app

  evaluation:
    image: dataprocessing-test
    build: .
    volumes:
      - .:/app
      - maven-repo:/root/.m2
    command: python3 evaluation/evaluation.py
    working_dir: /app

volumes:
  maven-repo:
