services:
  test:
    build: .
    command: ["npx", "jest", "--config", "jest.config.ts", "--verbose"]
    volumes:
      - .:/app
      - /app/node_modules

  meta-test:
    build: .
    command: ["npx", "jest", "--config", "jest.meta.config.ts", "--verbose"]
    volumes:
      - .:/app
      - /app/node_modules

  evaluation:
    build: .
    command: ["bash", "evaluation/evaluate.sh"]
    volumes:
      - .:/app
      - /app/node_modules
