services:
  before_test:
    build: .
    working_dir: /app
    command: "node -e \"console.log('before_test: node', process.version)\""
    volumes:
      - .:/app

  test_report:
    build: .
    working_dir: /app
    command: node --test --test-reporter spec
    volumes:
      - .:/app

  after_test:
    build: .
    working_dir: /app
    command: node evaluation/evaluation.js
    volumes:
      - .:/app
